POST http://localhost:3333/video
Content-Type: application/json
Accept-Language: pt-br


{
    "title":"Video node",
    "description":"Esse é o Segundo video",
    "duration":"140"
}

###

//GET  http://localhost:3333/video?search=node
GET  http://localhost:3333/video
###

PUT http://localhost:3333/video/067a5271-6a55-4d6f-91ee-f30938b0c776
Content-Type: application/json
Accept-Language: pt-br


{
    "title":"Video 12",
    "description":"Esse é o primeiro video",
    "duration":"180"
}

###
DELETE http://localhost:3333/video/067a5271-6a55-4d6f-91ee-f30938b0c776